# Generated by Django 5.1.2 on 2024-11-08 18:20

import django.db.models.deletion
import ptn_project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('search', '0002_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='CollaboratorMiddleTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('is_leader', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='KakaoTalk_Photo_2024-10-31-14-56-43.png', upload_to=ptn_project.models.discussion_image_upload_path)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_image', to='ptn_project.discussion')),
            ],
        ),
        migrations.CreateModel(
            name='InComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_comment', models.TextField(default='')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_in_comment', to='ptn_project.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_thumbnail', models.ImageField(default='KakaoTalk_Photo_2024-10-31-14-56-43.png', upload_to=ptn_project.models.thumbnail_upload_path)),
                ('simple_description', models.TextField(default='')),
                ('detail_description', models.TextField(default='')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('period', models.DateTimeField(auto_now_add=True)),
                ('link', models.TextField()),
                ('like_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('collaborator', models.ManyToManyField(related_name='collaborator_projects', through='ptn_project.CollaboratorMiddleTable', to='accounts.account')),
                ('like_accounts', models.ManyToManyField(related_name='like_projects', to='accounts.account')),
                ('project_genre', models.ManyToManyField(related_name='project', to='search.genretag')),
                ('project_platform', models.ManyToManyField(related_name='project', to='search.platform')),
                ('project_stack', models.ManyToManyField(related_name='project', to='search.stacktag')),
                ('project_university', models.ManyToManyField(related_name='project', to='search.universitytag')),
                ('scrap_accounts', models.ManyToManyField(related_name='scrap_projects', to='accounts.account')),
            ],
        ),
        migrations.AddField(
            model_name='discussion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='ptn_project.project'),
        ),
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='ptn_project.project'),
        ),
        migrations.AddField(
            model_name='collaboratormiddletable',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptn_project.project'),
        ),
        migrations.CreateModel(
            name='AIFeedbackSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_summary', models.TextField(default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback_summary', to='ptn_project.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='KakaoTalk_Photo_2024-10-31-14-56-43.png', upload_to=ptn_project.models.detail_image_upload_path)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_image', to='ptn_project.project')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_adopted', models.BooleanField(default=False)),
                ('feedback_description', models.TextField(default='')),
                ('feedback_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='accounts.account')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ptn_project.project')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='KakaoTalk_Photo_2024-10-31-14-56-43.png', upload_to=ptn_project.models.feedback_image_upload_path)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_image', to='ptn_project.userfeedback')),
            ],
        ),
    ]
