# Generated by Django 5.1.2 on 2024-11-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptn_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='period',
            field=models.TextField(default=''),
        ),
    ]
