# Generated by Django 5.1.2 on 2024-11-08 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ptn_project', '0001_initial'),
        ('search', '0002_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_platform',
            field=models.ManyToManyField(related_name='project', to='search.platform'),
        ),
        migrations.AlterField(
            model_name='aifeedbacksummary',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback_summary', to='ptn_project.project'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='ptn_project.project'),
        ),
        migrations.AlterField(
            model_name='commentincomment',
            name='parent_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_in_comment', to='ptn_project.comment'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='ptn_project.project'),
        ),
        migrations.AlterField(
            model_name='discussionimage',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_image', to='ptn_project.discussion'),
        ),
        migrations.AlterField(
            model_name='feedbackimage',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_image', to='ptn_project.userfeedback'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_image', to='ptn_project.project'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='feedback_writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ptn_project.project'),
        ),
    ]
