# Generated by Django 5.1.2 on 2024-11-06 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptn_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentInComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_in_comment', models.TextField(default='')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptn_project.comment')),
            ],
        ),
    ]
