# Generated by Django 5.1.2 on 2024-11-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptn_project', '0002_alter_project_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='view_count',
        ),
    ]
