# Generated by Django 5.1.2 on 2024-11-08 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptn_project', '0002_project_project_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_comment', models.TextField(default='')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_in_comment', to='ptn_project.comment')),
            ],
        ),
        migrations.DeleteModel(
            name='CommentInComment',
        ),
    ]
