# Generated by Django 5.1.2 on 2024-11-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptn_project', '0005_comment_comment_writer_discussion_discussion_writer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default='2024-11-11 02:11:19.535774'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discussion',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default='2024-11-11 02:11:19.535774'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomment',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default='2024-11-11 02:11:19.535774'),
            preserve_default=False,
        ),
    ]
