# Generated by Django 5.1.2 on 2024-11-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptn_project', '0008_alter_project_web_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='title',
            field=models.CharField(default='ex', max_length=255),
            preserve_default=False,
        ),
    ]
