# Generated by Django 5.1.2 on 2024-11-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptn_project', '0009_discussion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='android_link',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ios_link',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='web_link',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
