# Generated by Django 5.1.2 on 2024-11-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptn_project', '0010_alter_project_android_link_alter_project_ios_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='my_opinion',
            field=models.TextField(default=''),
        ),
    ]
