# Generated by Django 5.1.2 on 2024-11-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptn_project', '0011_userfeedback_my_opinion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='my_opinion',
        ),
    ]
