# Generated by Django 5.1.2 on 2024-11-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptn_project', '0012_remove_userfeedback_my_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='discussion',
            field=models.ManyToManyField(related_name='feedback', to='ptn_project.discussion'),
        ),
    ]
