# Generated by Django 5.1.2 on 2024-11-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptn_project', '0013_userfeedback_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aifeedbacksummary',
            name='title',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
