# Generated by Django 5.1.2 on 2024-11-13 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptn_project', '0014_aifeedbacksummary_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aifeedbacksummary',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aifeedbacksummary',
            name='feedback_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
