# Generated by Django 5.1.2 on 2024-11-14 17:20

import ptn_project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptn_project', '0016_alter_discussionimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_thumbnail',
            field=models.ImageField(default='thumbnail/default.png', null=True, upload_to=ptn_project.models.thumbnail_upload_path),
        ),
    ]
