# Generated by Django 5.1.2 on 2024-11-16 11:11

import ptn_project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptn_project', '0017_alter_project_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_thumbnail',
            field=models.ImageField(default='default.png', null=True, upload_to=ptn_project.models.thumbnail_upload_path),
        ),
    ]
