# Generated by Django 5.1.2 on 2024-11-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_name'),
        ('ptn_project', '0018_alter_project_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='collaborator',
            field=models.ManyToManyField(blank=True, related_name='collaborator_projects', through='ptn_project.CollaboratorMiddleTable', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
