# Generated by Django 5.1.2 on 2024-11-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptn_project', '0019_alter_project_collaborator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
