# Generated by Django 5.1.2 on 2024-11-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_name'),
        ('ptn_project', '0020_alter_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='collaborator',
            field=models.ManyToManyField(related_name='collaborator_projects', through='ptn_project.CollaboratorMiddleTable', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
