# Generated by Django 5.1.2 on 2024-11-06 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, unique=True)),
                ('total_point', models.IntegerField(default=0)),
                ('description', models.TextField(default='', max_length=255)),
                ('favorite_genre', models.ManyToManyField(related_name='account', to='search.genretag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.universitytag')),
            ],
        ),
    ]
